[SWTCH-299] Add filter enrollment requests
energywebfoundation/switchboard-dapp pull request #273
Opened 2021-05-24 08:10 UTC by DawidGil-jlabs

This PR is created by the request of Vadym.

2021-05-24 16:02 UTC, jrhender requested changes
@VOSpdUkraine I am getting an exception when navigating to the enrolment page for assets when running this branch. The exception doesn't seem to occur when trying the same action on https://switchboard-dev.energyweb.org/ Could you please confirm that this filtering works for assets as well when you have a moment?
![image](https://user-images.githubusercontent.com/4407464/119374314-ab3d0d80-bc76-11eb-8acf-1061f701cbec.png)
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at EnrolmentListComponent.<anonymous> (enrolment-list.component.ts:143)
    at Generator.next (<anonymous>)
```

2021-05-25 10:24 UTC, VOSpdUkraine commented
Hi @jrhender, Yes, thanks, I missed this exception, I fixed it

2021-05-26 17:08 UTC, jrhender approved these changes
Looks good to me

2021-05-27 09:06 UTC, DawidGil-jlabs commented on src/app/routes/enrolment/enrolment-list/enrolment-list.component.ts
> +        .subscribe((filterValue) => {
you don't need here `{ ...}`. It's fine to write `(filterValue) => this_updateList(filterValue)`

2021-05-27 12:21 UTC, merged