SWTCH-1270 create a role with other role as an issuer
energywebfoundation/switchboard-dapp pull request #504
Opened 2021-12-09 13:22 UTC by dawidgil

2021-12-09 20:11 UTC, jrhender requested changes
Getting an error: `Cannot read properties of undefined (reading 'issuer')`
![image](https://user-images.githubusercontent.com/4407464/145468592-a9869eab-a959-45c9-b1e8-aab3aaa6ab58.png)

2021-12-09 21:21 UTC, dawidgil commented
Updated. Should be good now.

2021-12-10 14:03 UTC, jrhender commented
@dawidgil better, but still not quite working for me. I'm not sure if this was there before but after I set a role to have a role as an issuer, I can't go back and edit the role https://www.loom.com/share/d7cd24c3eef7405e826484957483fd15

2021-12-10 14:27 UTC, dawidgil commented
ok... i will look on it. i checked it and it was working before :/

2021-12-10 14:44 UTC, dawidgil commented
ah, i watched this now. This is bug that i mentioned to you yesterday. I'm aware of it. This bug wasn't previously because this feature wasn't working 😈 . Right now just this information is not updated.
I mentioned that this one feature need refactoring + unit testing to be sure that it's working. However i will try to fix it on Monday.

2021-12-28 09:13 UTC, Malak67 approved these changes

2021-12-28 13:27 UTC, dawidgil commented on src/app/routes/applications/governance-view/governance-details/governance-details.component.html
> +        <ng-container *ngIf="formData?.definition?.issuer?.issuerType === 'ROLE'">
adjusted + I added few more methods and pipe :)

2022-01-04 18:51 UTC, jrhender approved these changes
Test locally. Looks great!

2022-01-04 19:28 UTC, merged