Update staging
energywebfoundation/switchboard-dapp pull request #893
Opened 2023-06-26 10:47 UTC by JGiter

2023-06-27 08:54 UTC, jrhender requested changes
Sorry @JGiter , I know it is confusing, but we shouldn't update `master` for Switchboard either. We should go directly from `develop` to `release`.

2023-06-27 08:58 UTC, JGiter commented
> Sorry @JGiter , I know it is confusing, but we shouldn't update `master` for Switchboard either. We should go directly from `develop` to `release`.

Ah, ok

2023-06-29 06:39 UTC, dawidgil approved these changes

2023-06-29 10:29 UTC, jrhender approved these changes

2023-06-29 10:31 UTC, merged